name = "ComoniconZSHCompletion"
uuid = "dcf03e4a-d036-4ede-96c9-024e9e9eed12"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ComoniconTypes = "d0eb39ce-029e-40d1-add6-e32b3165f6a3"

[compat]
ComoniconTypes = "0.2"
julia = "1.6.1"

[extras]
ComoniconTestUtils = "53b67e40-53a7-4335-973f-e3e901fe4865"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "ComoniconTestUtils"]
